#!/bin/sh

#global things
EMLOG_PLUGINS_PATH="/var/www/emlog/blog/content/plugins/"

while getopts r: folder
do
	case "$folder" in
		r)
			plugins_name=$OPTARG;;
		\?)
			echo 'USAGE: publish -r folder';;
	esac
done

if test -z "$plugins_name"
	then echo 'no input folder!'
		echo 'USAGE: publish -r folder'
		exit 1
fi

echo 'try to find plugins folder : '$plugins_name

#find the plugins folder
if [ -d $plugins_name ];
    then echo "find $plugins_name plugins" 
else 
	echo "$plugins_name is not a valid directory."
	exit 1
fi

#remove the older plugins
if [ -d $EMLOG_PLUGINS_PATH"/"$plugins_name ]
    then echo 'plugins already exsits.'
    rm $EMLOG_PLUGINS_PATH/$plugins_name -rf
	echo 'remove the older plugins.'
else
    echo 'the plugins is new to install.'
fi

#copy the new plugins
echo 'copy the plugins...'
cp $plugins_name $EMLOG_PLUGINS_PATH/$plugins_name -r
chmod 777 -R $EMLOG_PLUGINS_PATH/$plugins_name
echo 'upload finished!'
